# Container
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_MAX_ALLOWED_PACKET: 1073741824 # 1 GB
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - root_connection
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "1.0" # Batasi penggunaan CPU maksimal 1 core
          memory: "500m" # Batasi penggunaan RAM maksimal 500 MB

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dev
      PMA_USER: root # Menambahkan username root
      PMA_PASSWORD: dev # Menambahkan password root
      PMA_AUTH_TYPE: config # Menggunakan tipe otentikasi config
      UPLOAD_LIMIT: 500M
    ports:
      - "8083:80"
    depends_on:
      - mysql # Start Service after mysql running
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "0.5" # Batasi penggunaan CPU maksimal 0.5 core
          memory: "512m" # Batasi penggunaan RAM maksimal 512 MB

  mongodb:
    container_name: "mongodb"
    image: mongo:latest
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
    ports:
      - "8084:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "0.5" # Batasi penggunaan CPU maksimal 0.5 core
          memory: "512m" # Batasi penggunaan RAM maksimal 512 MB

  postgres:
    container_name: postgres
    image: postgres:15
    # restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "0.5" # Batasi penggunaan CPU maksimal 0.5 core
          memory: "512m" # Batasi penggunaan RAM maksimal 512 MB

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "256m"
          
networks:
  root_connection:
    external: true

volumes:
  mysql_data:
  mongo_data:
  postgres_data:
