# Version YML
version: "3.8"

# Container
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_MAX_ALLOWED_PACKET: 1073741824 # 1 GB
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "2.0"        # Batasi penggunaan CPU maksimal 2 core
          memory: "1g"       # Batasi penggunaan RAM maksimal 1 GB

  phpmyadmin:
    container_name: pma
    image: phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: dev
      PMA_USER: root # Menambahkan username root
      PMA_PASSWORD: dev # Menambahkan password root
      PMA_AUTH_TYPE: config # Menggunakan tipe otentikasi config
      UPLOAD_LIMIT: 500M
    ports:
      - "8080:80"
    depends_on:
      - mysql # Start Service after mysql running
    networks:
      - root_connection
    deploy:
      resources:
        limits:
          cpus: "0.5"        # Batasi penggunaan CPU maksimal 0.5 core
          memory: "512m"     # Batasi penggunaan RAM maksimal 512 MB

networks:
  root_connection:
    external: true

volumes:
  mysql_data:
